### ISSUE TITLE
Keine Kontaktmöglichkeit

### ISSUE THREAD

**Issue by Ahrdie** [bockstaller/Liederbuch#2]
Hi, wir würden gerne in unserem Liederbuch die Grafiken von Ariana benutzen und natürlich auch entsprechend kennzeichnen.
Leider ist ihr angegebener Instagram Account privat, weswegen ich nicht weiß, ob ihr das recht ist, wenn wir den angeben. Da würde ich gerne nochmal nachfragen, ob es andere Möglichkeiten gibt.
In der Lizenz steht zwar, dass @bockstaller kontaktiert werden kann, aber nicht wie (außer über Github Issues) 😀

Gut Pfad!

**Comment by bockstaller** [comment]
Hi @Ahrdie,
leider hab ich die Benachrichtigungen von meinem Github Account irgendwann mal leergeräumt und dein Issue mit enfernt. Ich vermute mal das du die Grafiken im Zweifelsfall schon längst verwendet hast. Das ist absolut cool. Wenn du allerdings noch 1-2 Exemplare über hättest würde ich mich sehr darüber freuen. Dann könnten wir jeweils unserer Künstlerin und dem AK Archiv eine Kopie zukommen lassen.
Falls das geht würde ich dir die Adresse an deine contact@r****tdeppe.de Adresse schicken.

Ich passe auch gleich die Lizenz an

**Comment by Ahrdie** [comment]
Ich glaube bei uns im DV Büro liegen noch welche, ich frage mal nach, ob man euch etwas zuschicken könnte. Schick mir schonmal die Adresse zu.

**Comment by bockstaller** [comment]
Du kommst nicht zufälligerweise aus dem DV Essen? Falls ja hab ich schon Kontakt mit dem DV Büro
